version: '3.8'

services:
  frontend:
    command: 'yarn serve'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
