<template>
  <div class="loader-wrapper">
    <transition appear name="fade">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        class="loader-svg"
        width="200px"
        height="200px"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
      >
        <circle cx="28" cy="75" r="11" fill="#0051a2">
          <animate
            attributeName="fill-opacity"
            repeatCount="indefinite"
            dur="1s"
            values="0;1;1"
            keyTimes="0;0.2;1"
            begin="0s"
          ></animate>
        </circle>

        <path
          d="M28 47A28 28 0 0 1 56 75"
          fill="none"
          stroke="#1b75be"
          stroke-width="10"
        >
          <animate
            attributeName="stroke-opacity"
            repeatCount="indefinite"
            dur="1s"
            values="0;1;1"
            keyTimes="0;0.2;1"
            begin="0.1s"
          ></animate>
        </path>
        <path
          d="M28 25A50 50 0 0 1 78 75"
          fill="none"
          stroke="#408ee0"
          stroke-width="10"
        >
          <animate
            attributeName="stroke-opacity"
            repeatCount="indefinite"
            dur="1s"
            values="0;1;1"
            keyTimes="0;0.2;1"
            begin="0.2s"
          ></animate>
        </path>
        <!-- [ldio] generated by https://loading.io/ -->
      </svg>
    </transition>
  </div>
</template>

<style lang="scss">
.loader {
  &-wrapper {
    display: flex;
    justify-content: center;
    align-items: center;
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    z-index: 10;
  }
  &-svg {
    background: transparent;
    shape-rendering: auto;
  }
}
</style>
