name: Deps, lint and test
on: [push]
jobs:
  Deps-Lint-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i yarn -D
      - run: npx yarn
      - run: npx yarn lint
      - run: npx yarn test:unit
